name: DiscordBot
version: '${project.version}'
main: dk.shadow.discordbot.Main
api-version: 1.8
authors: [ Shad0wsense ]
description: none
website: mcstore.dk
commands:
  verify:
    description: "Hej"