DiscordBot:
  Token: "ODU3OTcwMTU4MTk3ODAwOTgw.GuV-0S.Vae4p1kwn4xCyY4FOXFLtwVXylOZcquy4XvYh8"
  Spiller: "Jeg spiller minecraft"
  Guild: 1107768180191015048

  #VERIFY
  verify-channel:
  verify-role-id:


messages:
  verify-message: "&8&l[ &a&LVERIFY &8&L] &fDin kode er &a%kode% &fBrug /link <kode> på discord"
  verify-med: "&8&l[ &a&LVERIFY &8&L] &a%player% &fverifyed med &a%discord-username%"