name: DiscordBot
version: '1.0'
main: dk.shadow.discordbot.Main
api-version: 1.8
authors: [ Shad0wsense ]
description: "A discord bot"
website: mcstore.dk
commands:
  verify:
    description: "The verify command"
    aliases:
      - link